### ISSUE TITLE
Provide Docker Image in GitHub Registry

### ISSUE THREAD

**Issue by Robbilie** [github/github-team-sync#119]
We would like to run this application as a docker container in a kubernetes Cluster and right now we would have to build the image ourselves.

Since GitHub makes it really easy to publish docker images it would be great if this functionality could be added to the pipeline of a release (possibly main branch too).

If you want I can provide a pull request, configuration for making the artifact public would have to be done by the maintainers though...

**Comment by primetheus** [comment]
solved in #125
