### ISSUE TITLE
Python versioning changed ? 

### ISSUE THREAD

**Issue by maestro1315** [github/github-team-sync#135]
I'm receiving the below error when building in Docker. 

#11 1.618 Warning: Python 3.9 was not found on your system...
#11 1.620 Neither 'pyenv' nor 'asdf' could be found to install Python.
#11 1.620 You can specify specific versions of Python with:
#11 1.620 $ pipenv --python path/to/python

Changing to the below in the pipfile gets me further but then I receive errors during the pipenv install step.

[requires]
python_version = "3.10"

**Comment by maestro1315** [comment]
Changing to the below gets me further but then I receive errors during the pipenv install step. 

[requires]
python_version = "3.10"

**Comment by GolanTrevize10** [comment]
I had the same issue, check #126
