### ISSUE TITLE
Add support in Github API to modify team sync settings

### ISSUE THREAD

**Issue by mattbryce93** [github/github-team-sync#143]
Due to a limitation in the API, it is not possible to modify the Groups that a team syncs with.

Please add a ldap_dn field in the teams API endpoint to allow for this adjustment as currently it is impossible to automate team creation in Github with syncing automatically enabled.

Relevant Endpoint for Github Cloud (field missing): https://docs.github.com/en/rest/teams/teams#get-a-team-by-name
Relevant Endpoint for Github Server (field present): https://docs.github.com/en/enterprise-server@3.3/rest/teams/teams#get-a-team-by-name

Example for Terraform using this property: https://registry.terraform.io/providers/integrations/github/latest/docs/resources/team#ldap_dn

**Comment by igorcosta** [comment]
Just closing this issue as turns out the @mattbryce93  was more looking for IDP groups on SAML.
