### ISSUE TITLE
Rename Repository

### ISSUE THREAD

**Issue by primetheus** [github/github-team-sync#59]
Since we have implemented `Azure AD` (#56), `Okta` (#58) and `OneLogin` (#60) support, having the name specifically tied to LDAP no longer makes sense. Additional providers can easily be added with the current framework

## Suggestions
- SAML-LDAP-TeamSync (the original name)
- TeamSync
- others?

**Comment by parkerbxyz** [comment]
The README title is "GitHub Team Sync" so I think either `github -team-sync` or `team-sync` would make sense.

**Comment by primetheus** [comment]
I think `github-team-sync` is probably best, so we don't confuse anyone that it might work with other platforms
