### ISSUE TITLE
Custom attribute not used

### ISSUE THREAD

**Issue by amanske** [github/github-team-sync#85]
https://github.com/github/github-team-sync/blob/2f317527b753c0a98210f0adfcd3f4cb14b0b9d1/githubapp/okta.py#L66

The hardcoded value `github_username` is used instead of the custom attribute `USERNAME_ATTRIBUTE`. This line should be `"username": getattr(user.profile, self.USERNAME_ATTRIBUTE),`

**Comment by anonymousr007** [comment]
Hi @primetheus, I'm Rishabh from India, Can we contribute in this issue ?

**Comment by primetheus** [comment]
@anonymousr007 yes, pull requests to this are open and encouraged. This seems like a simple fix, but I need to fix my Okta account before I can implement a fix myself
